### ISSUE TITLE
7zip.json在运行post_install阶段的时候报错。

### ISSUE THREAD

**Issue by sdh1986** [duzyn/scoop-cn#1]
PS C:\Users\xxx> scoop install https://ghproxy.com/raw.githubusercontent.com/duzyn/scoop-cn/master/bucket/7zip.json
Installing '7zip' (22.01) [64bit]
7z2201-x64.msi (1.8 MB) [===========================================================================] 100%
Checking hash of 7z2201-x64.msi ... ok.
Extracting 7z2201-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\22.01
Creating shim for '7z'.
Creating shim for '7zFM'.
Creating shim for '7zG'.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Running post_install script...
Get-Content : 找不到路径“C:\Users\xxx\scoop\buckets\scoop-cn\scripts\7-zip\install-context.reg”，因为该
路径不存在。
所在位置 行:3 字符: 16
+     $content = Get-Content "$bucketsdir\scoop-cn\scripts\7-zip\$_"
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\xxx...all-context.reg:String) [Get-Content], Item
   NotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

**Comment by duzyn** [comment]
这是因为初次在安装 7-Zip、Git 的时候，scoop-cn 这个应用库还没有添加，所以没有 scripts 文件夹，也没有注册表文件，所以会有报错，但是应用是安装成功了的，不影响继续后面的安装步骤的。
如果想解决这个报错，可以在安装完 7-Zip、Git 之后，添加 scoop-cn 这个应用库，然后卸载 7-Zip、Git 后重新从 scoop-cn 安装一次

```
scoop uninstall 7zip git
scoop install scoop-cn/7zip
scoop install scoop-cn/git
```

这样做的另一好处是，后续可以从 scoop-cn 接收到 7zip 和 git 的更新。
我已在 README.md 中加入了这一步骤。
感谢你的反馈~
