### ISSUE TITLE
OBS可更换github仓库地址

### ISSUE THREAD

**Issue by lentikr** [duzyn/scoop-cn#11]
OBS目前使用的源速度较慢，可以使用github镜像中的仓库地址，例如：https://mirror.ghproxy.com/https://github.com/obsproject/obs-studio/releases/download/30.1.2/OBS-Studio-30.1.2.zip

**Comment by duzyn** [comment]
感谢反馈。
问题原因：OBS 从版本 v29 起改变了安装包文件名的命名规则，去掉了原来的 “-Full” 字样，导致之前替换下载链接地址的正则表达式失效了。
现在 OBS 的下载链接地址已经修正了。
