### ISSUE TITLE
wechat@3.9.10.19: hash check failed

### ISSUE THREAD

**Issue by Josecep** [duzyn/scoop-cn#15]
Checking hash of WeChatSetup.exe ... ERROR Hash check failed!
App:         scoop-cn/wechat
URL:         https://dldir1v6.qq.com/weixin/Windows/WeChatSetup.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    9602acb85408ee48ee689468f63565496dfb12f1fe21ad674aa423029e38856c
Actual:      bd230520ab8debf42c282f067c55583b90f3ca11d5b929a99aeb3af51f9d23ea

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/duzyn/scoop-cn/issues/new?title=wechat%403.9.10.19%3a+hash+check+failed

**Comment by duzyn** [comment]
可能是上游bucket extras 中的问题，因为 wechat.json 并没有改安装包下载地址，我试了最新版本的微信已没有问题

```
scoop download scoop-cn/wechat
Updating Scoop...
Updating Buckets...
Scoop was updated successfully!
INFO  Downloading 'wechat' [64bit] from scoop-cn bucket
WeChatSetup.exe (245.2 MB) [==================================================================================] 100%
Checking hash of WeChatSetup.exe ... ok.
'wechat' (3.9.11.17) was downloaded successfully!
```
