### ISSUE TITLE
更换安装路径后，安装报错

### ISSUE THREAD

**Issue by gatspy** [duzyn/scoop-cn#22]
`scoop-cn` bucket 还是安装到了 `~/scoop`中

![局部截取_20241026_063301](https://github.com/user-attachments/assets/5b2ea324-9bea-44ba-be1a-76dd897610a6)

**Comment by duzyn** [comment]
因为现在install那个ps脚本并没有响应环境变量。

**Comment by gatspy** [comment]
是的，设置的SCOOP变量没起作用，这个会修复吗

**Comment by duzyn** [comment]
现在已修复了，可以响应SCOOP变量。重新运行安装命令即可

irm https://mirror.ghproxy.com/https://raw.githubusercontent.com/duzyn/scoop-cn/master/install.ps1 | iex
