### ISSUE TITLE
autohotkey1.1 cannot set the ahk file suffix to open by default after installation

### ISSUE THREAD

**Issue by DreamMaoMao** [duzyn/scoop-cn#23]
There seems to be a missing registration process for file extensions

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/scoop-cn/commit/a6760d75a1b17bae8d6a525baa1c71c77ef2fd6b
我把注册表的扩展名加上了也还是不行，不知道还缺了哪个安装步奏

**Comment by duzyn** [comment]
这个问题感觉你应该反馈到 https://github.com/ScoopInstaller/Versions，autohotkey1.1.json 是那个项目中的。我只是搬运过来了。
