### ISSUE TITLE
性能优化 update.ps1

### ISSUE THREAD

**Issue by yb6b** [duzyn/scoop-cn#24]
原代码里有大量的

```powershell
(Get-Content $_.FullName) -replace 'a', 'b' | Set-Content -Path $_.FullName
(Get-Content $_.FullName) -replace 'c', 'd' | Set-Content -Path $_.FullName
```

每条替换规则都需要读文件、写文件。建议把 Get-Content 的结果提取到变量里，在对这个变量应用转换。

我[试了一下](https://github.com/yb6b/scoop-cn/blob/master/update.ps1)，脚本在 Github Actions 里的耗时，从4分多钟减少到19秒，这种优化是值得的。

**Comment by duzyn** [comment]
多谢你的建议，已将你的改进合入了脚本。
