### ISSUE TITLE
blender4.3.2 阿里云镜像无此版本

### ISSUE THREAD

**Issue by gatspy** [duzyn/scoop-cn#27]
blender的源能换成清华镜像吗？镜像最好还是不要用阿里云的

**Comment by duzyn** [comment]
多谢你的反馈，已将阿里云镜像都已改成了校园网镜像。
现在优先使用清华大学的镜像，其次是中科大的，再是南京大学的

**Comment by gatspy** [comment]
感谢感谢，终于不用自己手动修改地址再还原了
