### ISSUE TITLE
指定scoop安装目录和global apps 安装目录怎么办？

### ISSUE THREAD

**Issue by jiuyueshenhua** [duzyn/scoop-cn#4]
如果我想指定scoop安装目录和global apps 安装目录怎么办？官方文档是先下安装包，再指定参数。试图模仿尝试了一下。
把（irm https://ghproxy.com/https://raw.githubusercontent.com/duzyn/scoop-cn/master/install.ps1 | iex）的iex删了，（小白看不懂命令，猜这样就只是下载安装包，而不会去安装）
然后输入 （.\install.ps1 -? ）
终端显示 (The term '.\install.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.）
看起来这条路走不通，所以应该怎么做呢？

**Comment by duzyn** [comment]
可以先设置 SCOOP 环境变量后，再运行安装，例如

$env:SCOOP='D:\Applications\Scoop'
irm https://ghproxy.com/https://raw.githubusercontent.com/duzyn/scoop-cn/master/install.ps1 | iex

参考 [Scoop 官方文档](https://github.com/ScoopInstaller/Install#advanced-installation)，老方法是设环境变量，老方法仍然有效。

**Comment by jiuyueshenhua** [comment]
谢谢大佬回答，那顺便问一下代理问题。
我在PowerShell里，curl 油管的网址成功了，但是 curl github里，短暂显示一串蓝色的读取条后，就没动静了，一直卡住。敲键盘也没反应。官方scoop访问GitHub有问题，在官方scoop里设置了代理（ scoop config proxy 127.0.0.1:7890 ）也没用。不知这是什么原因。

**Comment by jiuyueshenhua** [comment]
> 可以先设置 SCOOP 环境变量后，再运行安装，例如
> 
> ```
> $env:SCOOP='D:\Applications\Scoop'
> $env:SCOOP_GLOBAL='F:\GlobalScoopApps'
> [Environment]::SetEnvironmentVariable('SCOOP_GLOBAL', $env:SCOOP_GLOBAL, 'Machine')
> irm https://ghproxy.com/https://raw.githubusercontent.com/duzyn/scoop-cn/master/install.ps1 | iex
> ```
> 
> [Scoop 官方文档](https://github.com/ScoopInstaller/Install#advanced-installation) 有写的，这是老方法，老方法是设环境变量，目前仍然有效。

还是有问题。第三条命令需要管理员运行权限。可允许管理员权限后scoop官方又禁止在管理员权限下载。

**Comment by jiuyueshenhua** [comment]
> > 可以先设置 SCOOP 环境变量后，再运行安装，例如
> > ```
> > $env:SCOOP='D:\Applications\Scoop'
> > $env:SCOOP_GLOBAL='F:\GlobalScoopApps'
> > [Environment]::SetEnvironmentVariable('SCOOP_GLOBAL', $env:SCOOP_GLOBAL, 'Machine')
> > irm https://ghproxy.com/https://raw.githubusercontent.com/duzyn/scoop-cn/master/install.ps1 | iex
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [Scoop 官方文档](https://github.com/ScoopInstaller/Install#advanced-installation) 有写的，这是老方法，老方法是设环境变量，目前仍然有效。
> 
> 还是有问题。第三条命令需要管理员运行权限。可用管理员权限执行命令后scoop官方又默认在管理员权限下禁止安装。

对了，我使用$PSVersionTable.PSVersion.Major 查询版本 是5.0 但是  $psversiontable 查询版本是5.1 。
在执行（ Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser） 时 终端没有进行任何提问。
这是否与PowerShell的版本有问题？

![image](https://github.com/duzyn/scoop-cn/assets/109449284/24c8bc4b-4834-408b-b6b6-c44d3e1e29f9)

**Comment by duzyn** [comment]
你的ps版本没问题。前三条命令用管理员运行，第四条不用。

**Comment by jiuyueshenhua** [comment]
> 你的ps版本没问题。前三条命令用管理员运行，第四条不用。

不行，还是会下载到C盘。
然后我 scoop uninstall scoop ，但 raise access is denied 了！。查阅资料，决定手动删除了C盘下与Scoop相关的文件。
然后我在这四条命令上，查阅资料，得还要补充一句 ：[Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'User')
重新执行下载安装命令后出现了以下问题：
安装后 下载 git，aria2, 7-zip 后失败，显示什么 东西不存在（单词不认识）。可惜没来得及截图。
能从scoop-cn 下载东西（已下了git，aria2,clion,7-zip)，但是搜索 scoop-cn 的软件会失败。
![image](https://github.com/duzyn/scoop-cn/assets/109449284/105daf0f-0363-4019-9012-d924c8e70309)

但是scoop 本身似乎没啥问题。
虽然途径坎坷但还是很感谢你。
这几天因为网络代理问题反反复复下载了scoop十几次，每一次换源，配置都把scoop整烂了。大佬的scoop-cn真的帮我了很大忙！

**Comment by duzyn** [comment]
搜索app，使用 `scoop search APPNAME`。我之前写错了

**Comment by LXTlogic** [comment]
实际上，你可以不使用环境变量指定安装位置，环境变量确实可以解决安装位置的问题，但即使是官方安装手册上也并不建议使用环境变量（仓库ReadMe文件中环境变量来指定安装位置是不推荐的），在官方手册Advanced Installation一节中指出安装时在指令末尾加入 `-ScoopDir "安装位置"` 以及 `-ScoopGlobalDir “全局安装位置”`是可以不使用环境变量的。因此，可以使用`irm get.scoop.sh -outfile 'install.ps1'` 将安装脚本下载到当前目录下，然后使用 `.\install.ps1 -ScoopDir 'D:\Tools\Scoop\Apps' -ScoopGlobalDir 'D:\Tools\Scoop\GlobalApps' -ScoopCacheDir 'D:\Tools\Scoop\GlobalApps\Temporary\ScoopCache'` 来分别指定 Scoop 安装应用的位置以及缓存存储的位置。
[可以看看我混乱的Scoop文档](https://github.com/LXTlogic/SharpTools/blob/master/Doc/Scoop%E6%8C%87%E5%8D%97.md#3-%E9%AB%98%E7%BA%A7%E5%AE%89%E8%A3%85%E5%AE%98%E7%BD%91%E6%8E%A8%E8%8D%90)
注意官方指南中的安装最后的 `-NoProxy` 项会使Scoop不走代理

**Comment by LXTlogic** [comment]
> 实际上，你可以不使用环境变量指定安装位置，环境变量确实可以解决安装位置的问题，但即使是官方安装手册上也并不建议使用环境变量（仓库ReadMe文件中环境变量来指定安装位置是不推荐的），在官方手册Advanced Installation一节中指出安装时在指令末尾加入 `-ScoopDir "安装位置"` 以及 `-ScoopGlobalDir “全局安装位置”`是可以不使用环境变量的。因此，可以使用`irm get.scoop.sh -outfile 'install.ps1'` 将安装脚本下载到当前目录下，然后使用 `.\install.ps1 -ScoopDir 'D:\Tools\Scoop\Apps' -ScoopGlobalDir 'D:\Tools\Scoop\GlobalApps' -ScoopCacheDir 'D:\Tools\Scoop\GlobalApps\Temporary\ScoopCache'` 来分别指定 Scoop 安装应用的位置以及缓存存储的位置。 [可以看看我混乱的Scoop文档](https://github.com/LXTlogic/SharpTools/blob/master/Doc/Scoop%E6%8C%87%E5%8D%97.md?rgh-link-date=2023-08-20T15%3A56%3A20Z#3-%E9%AB%98%E7%BA%A7%E5%AE%89%E8%A3%85%E5%AE%98%E7%BD%91%E6%8E%A8%E8%8D%90) 注意官方指南中的安装最后的 `-NoProxy` 项会使Scoop不走代理

注意Scoop 的配置文件位于用户目录下的 `.config\scoop\config.json`
