### ISSUE TITLE
请问如果之前有官方的scoop安装要切换到scoop-cn有什么需要注意吗？

### ISSUE THREAD

**Issue by neolee** [duzyn/scoop-cn#5]
非常感谢这个repo做的工作，看表述应该能造福很多人。

我的一个小问题如标题：请问如果之前有官方的scoop安装要切换到scoop-cn有什么需要注意吗？可以直接安装 scoop-cn 来覆盖不？毕竟之前装了不少软件包，全部重来一遍还有点麻烦……

**Comment by duzyn** [comment]
每个app安装后在app的current路径下有个install.json，里面的bucket项的值改为scoop-cn，这样就把已安装的app换到scoop-cn了。可以运行scoop list 来检查替换成功。如果要批量修改，可以借助grepWin来写个正则表达式搜索替换这个值。

**Comment by neolee** [comment]
> 每个app安装后在app的current路径下有个install.json，里面的bucket项的值改为scoop-cn，这样就把已安装的app换到scoop-cn了。可以运行scoop list 来检查替换成功。如果要批量修改，可以借助grepWin来写个正则表达式搜索替换这个值。

谢谢~

所以，要把已经安装过官方版本scoop的环境改为scoop-cn，是不是做这么两步就可以了呢：
1. 运行scoop-cn的安装脚本，确保以后新的scoop操作都是scoop-cn模式；
2. 然后，如你所说，根据需要修改已安装软件的bucket。

**Comment by duzyn** [comment]
既然你已经安装了 Scoop，不用运行scoop-cn的安装脚本，只需添加本 bucket 即可，运行命令 `scoop bucket add scoop-cn https://ghproxy.com/https://github.com/duzyn/scoop-cn` ，然后根据需要修改已安装软件的bucket。

**Comment by neolee** [comment]
> 既然你已经安装了 Scoop，不用运行scoop-cn的安装脚本，只需添加本 bucket 即可，运行命令 `scoop bucket add scoop-cn https://ghproxy.com/https://github.com/duzyn/scoop-cn` ，然后根据需要修改已安装软件的bucket。

明白了，这种方式确实很轻量级也很方便，多谢~
