### ISSUE TITLE
ghproxy.com加速失效

### ISSUE THREAD

**Issue by 3q3z4** [duzyn/scoop-cn#7]
如题

**Comment by duzyn** [comment]
https://ghproxy.com/ 现在无法访问，只能等他恢复了

**Comment by xbxcw** [comment]
能改成githubfast.com吗。这个还可以用

**Comment by duzyn** [comment]
> 能改成githubfast.com吗。这个还可以用

githubfast.com这个我试了下，用aria2无法下载app，但同样的url wget和free download manager却是可以下载的。看来这是aria2的bug。参看 https://github.com/ScoopInstaller/Scoop/issues/5341

**Comment by xbxcw** [comment]
嗯嗯，我是把aria2关了的

**Comment by Techoc** [comment]
`https://gh-proxy.com/`这个还可以用

**Comment by felixmaker** [comment]
我也用不了了

**Comment by duzyn** [comment]
> `https://gh-proxy.com/`这个还可以用

已将代理切换到gh-proxy了，现在可以正常使用了

**Comment by toshiya14** [comment]
https://hub.fgit.cf/duzyn/scoop-cn.git
