### ISSUE TITLE
search

### ISSUE THREAD

**Issue by Abrillant-Lee** [duzyn/scoop-cn#9]
使用 `scoop search xxx` 命令检索软件的时候，特别慢，需要2min才能出结果

**Comment by duzyn** [comment]
因为scoop本身的性能问题，search命令特别慢。有以下办法可尝试
1、使用scoop-search，运行 scoop install scoop-search 安装，然后用 scoop-search APPNAME
2、 直接用Everything 搜索本地文件，运行 scoop install everything 安装。
我个人用第二种多一些

**Comment by Abrillant-Lee** [comment]
> 因为scoop本身的性能问题，search命令特别慢。有以下办法可尝试 1、使用scoop-search，运行 scoop install scoop-search 安装，然后用 scoop-search APPNAME 2、 直接用Everything 搜索本地文件，运行 scoop install everything 安装。 我个人用第二种多一些

> 感谢回答，使用第一种方法：scoop-search工具确实使检索过程加快。
> 我需要的是从buckets中获取软件，而不是本地，所以第二种方法使用everything是检索本地文件不符合个人的使用
